# -*- coding: utf-8 -*-
"""Netflix Project Final main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144WdkykyK7Rw5SmP6du-NY1U_KpBUcLj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns





netflix_dataset = pd.read_csv('/content/drive/MyDrive/Netflix Dataset/Copy of combined_data_1.txt.zip', header =None , names=['Cust_Id' , 'Ratings'] , usecols=[0,1])

netflix_dataset

movie_count = netflix_dataset.isnull().sum()
movie_count = movie_count['Ratings']
movie_count

total_count = netflix_dataset['Cust_Id'].nunique()

customer_count = total_count-movie_count
customer_count

rating_count= netflix_dataset['Cust_Id'].count()- movie_count

rating_count

stars = netflix_dataset['Ratings'].value_counts()

stars

movie_id = None
movie_np = []

for customer in netflix_dataset['Cust_Id']:
  if ":" in customer:
    movie_id = int(customer.replace(":"  , ""))


  movie_np.append(movie_id)

movie_np

netflix_dataset['Movie_Id'] = movie_np

netflix_dataset.dropna(inplace=True)

netflix_dataset

netflix_dataset.info()

netflix_dataset['Cust_Id']=netflix_dataset['Cust_Id'].astype(int)

netflix_dataset.info()

movie_re_count = netflix_dataset['Movie_Id'].value_counts()

#movie_re_count= netflix_dataset.groupby('Ratings')['Ratings'].agg('count')

movie_re_count

bench_mark = round(movie_re_count.quantile(0.6) , 0)  #48.0 --> 48

bench_mark

drop_movie_index = movie_re_count[movie_re_count<bench_mark].index

drop_movie_index

cust_rew_count = netflix_dataset['Cust_Id'].value_counts()

cust_rew_count

bench_mark_cus = round(cust_rew_count.quantile(0.6),0)

bench_mark_cus

drop_cust_index = cust_rew_count[cust_rew_count<bench_mark_cus].index

drop_cust_index

drop_movie_index , drop_cust_index

netflix_dataset = netflix_dataset[~netflix_dataset['Movie_Id'].isin(drop_movie_index)]
netflix_dataset = netflix_dataset[~netflix_dataset['Cust_Id'].isin(drop_cust_index)]

netflix_dataset

movie_title = pd.read_csv('/content/drive/MyDrive/Netflix Dataset/Copy of movie_titles.csv', encoding ='ISO-8859-1', header =None , names=['Movie_Id' , 'Year' ,'Name'] , usecols=[0,1,2])

movie_title



#!pip install numpy==1.23.5

from surprise import SVD ,  Reader , Dataset
from surprise.model_selection import cross_validate

reader = Reader()

data = Dataset.load_from_df(netflix_dataset[['Movie_Id' , 'Cust_Id' , 'Ratings']][:100000], reader)

data

model = SVD()

cross_validate(model , data , measures=['RMSE'] , cv=3)

user_rating = netflix_dataset[netflix_dataset['Cust_Id'] == 1331154]

user_rating

user_1331154 = movie_title.copy()
user_1331154

user_1331154 = user_1331154[~user_1331154['Movie_Id'].isin(drop_movie_index)]



user_1331154

user_1331154['Estimated']=user_1331154['Movie_Id'].apply(lambda x:model.predict(1331154,x).est)

user_1331154

user_1331154.sort_values('Estimated' , ascending=False)

user_1331154.head()

popular_genres = df['genre'].value_counts().reset_index()
popular_genres.columns = ['Genre']



#!pip show numpy surprise

#!pip install numpy==1.23.5